spring:
  datasource:
    name: tchmanage
    url: jdbc:mysql://localhost:3306/tchmanage?serverTimezone=GMT
    username: root
    password: sc198831430
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/UsersMapper.xml
  type-aliases-package: com.sicnu.tchmanage.bean
